### ISSUE TITLE
Pull requests temporarily on hold

### ISSUE THREAD

**Issue by t-14** [AdaCore/gnatcoll-core#1]
Dear contributors,

Following the switch to modular organization, we are working on the testsuite refactoring. Before the testsuite is in place we can't accept pull requests.

We apologize in advance, and thank you for your patience!

**Comment by briot** [comment]
Is this still accurate ? I believe you have merged a few patches since then

**Comment by t-14** [comment]
Indeed, that's OBE, thanks for the heads up.
