### ISSUE TITLE
GNATCOLL.PROJECTS : Tree.Load takes a very long time (minutes) on files resulting from fuzzing

### ISSUE THREAD

**Issue by touisteur** [AdaCore/gnatcoll-core#10]
Hi,

I'm fuzzing GNATCOLL.PROJECTS, and facing a strange "hanging" case. I think I must be doing something wrong.

I created the simplest project making use of GNATCOLL.PROJECTS (I copied and trimmed down another test from the project, hence the name "Iter") : 

```
with GNATCOLL.Projects; use GNATCOLL.Projects;
with GNATCOLL.VFS;      use GNATCOLL.VFS;
with Ada.Text_IO;       use Ada.Text_IO;

with Ada.Command_Line;
with Ada.Exceptions;
with GNAT.Exception_Actions;

procedure Iter
is
   Tree : Project_Tree;
   Filename : constant String := Ada.Command_Line.Argument (1);
begin
   Tree.Load (GNATCOLL.VFS.Create (+Filename));
exception -- for fuzzing, we want to
          -- inform afl-fuzz that we crashed (call abort())
          -- only on "uncontrolled exceptions
   when GNATCOLL.Projects.Invalid_Project => null;
   when Occurence : others =>
      Ada.Text_IO.Put_Line ("exception occured for " & Filename
                            & " [" & Ada.Exceptions.Exception_Name (Occurence)
                            & "] ["
                            & Ada.Exceptions.Exception_Message (Occurence)
                            & "] ["
                            & Ada.Exceptions.Exception_Information (Occurence)
                            & "]");
      GNAT.Exception_Actions.Core_Dump (Occurence);
end Iter;
```

and I've compiled it with GNATCOLL GPL 2016 and GNAT GPL 2016. The fuzzer provided me with test cases that take a *very long time* to open (more than a minute). [gnatcoll-project-hangs.zip](https://github.com/AdaCore/gnatcoll-core/files/1503484/gnatcoll-project-hangs.zip)

My test hardware is slow but not that slow (it can open 20-30 projets per second). In fact I haven't waited for the end of the execution (several minutes), and instead went to PMP (https://poormansprofiler.org/), and with a simple gdb+bash script : 
```

#!/bin/bash
nsamples=10000
sleeptime=0
pid=$1

for x in $(seq 1 $nsamples)
  do
    gdb -ex "set pagination 0" -ex "thread apply all bt" -batch -p $pid
    sleep $sleeptime
  done
```
and got a trace [gnatcoll-project-hang-28499.txt](https://github.com/AdaCore/gnatcoll-core/files/1503483/gnatcoll-project-hang-28499.txt) for id:000000*.

BR
Lionel

**Comment by t-14** [comment]
> GNATCOLL GPL 2016 and GNAT GPL 2016

As I've said already, this configuration is of no interest to man or beast. We will only accept issues for the most up-to-date version. Please use GPL 2017 for the compiler, and both gnatcoll and libgpr (which is used by gnatcoll.projects) at their latest revision on github. Otherwise it's a waste of time for both you and us. With recent version your test works fine with no delay:

```
$ iter add_attr.gpr
add_attr.gpr:1:01: illegal character
```

But even version obsolescence aside, generally speaking, I don't see any value in fuzzy-testing projects facility. We are much more interested in reports of real projects misbehaving, than artificial cases that have no chance of occurring in practice.

**Comment by touisteur** [comment]
Hi @t-14,

> As I've said already, this configuration is of no interest to man or beast. We will only accept issues for the most up-to-date version. Please use GPL 2017 for the compiler, and both gnatcoll and libgpr (which is used by gnatcoll.projects) at their latest revision on github.

I hadn't gathered that you wouldn't accept reports on a previous version, just that it wasn't the greatest thing to do. Fine then.

> But even version obsolescence aside, generally speaking, I don't see any value in fuzzy-testing projects facility. We are much more interested in reports of real projects misbehaving, than artificial cases that have no chance of occurring in practice.

Well, that's your opinion. I think you underestimate the amount of data that is corrupted every minute, in absence of ECC, with shoddy hard drives, and as you say in another issue "cosmic rays"... With the little experience I have with fuzzing, it often reveals problems somewhere else, and nobody had remaked yet on the futility of it. Of course you're more interested in "real" projects, and of course I'm sure you care about the future user that'll get a strange crash because he mistyped (happens all the time on my linux box, strange utf characters get inserted because I "type too fast" - or so says my sysadmin :-D) or had the misfortune to have a disk crash that seemed resolved but no.

It's fine that the problem isn't there anymore, and it probably means that it was corrected somehow. Usually when a user reports a bug on my software (very rarely the latest version) and it doesn't appear anymore in the latest version I make a point of tracking down the correction to make sure it is *really* corrected. I'm not asking you to do this, of course ! I'm just trying to explain why I thought the bug report might be useful even though it was on an old version.

And with the GNATCOLL repository in flux these days, I wasn't sure how to re-start all this test job.

I'm really sorry you lost so much of your time, Vasiliy. I don't feel like I lost any of mine :-), and it was all done in good faith.

You're free of course to close all the opened issues on the ground that they're on an old version and that you're not interested by artificial cases, etc. I'd just thought that it'd be useful in some way, and that you might be interested.

Moving on.
