### ISSUE TITLE
gnatcoll.sql* should be moved to AdaCore/gnatcoll-db

### ISSUE THREAD

**Issue by briot** [AdaCore/gnatcoll-core#12]
Those packages are useless without either sqlite or postgresql backends, which are both in the other repository. Splitting them also makes it harder to contribute patches, since we are likely to impact both repositories, and thus need to synchronize patches. That also makes it harder for you to merge pull requests.

Given the name 'gnatcoll-db', I guess that's where people will expect to find gnatcoll.sql

Thanks

**Comment by Nikokrock** [comment]
When splitting gnatcoll in several pieces we thought that some core elements such as traces had direct dependencies on gnatcoll.sql. That's the reason why we kept sql inside gnatcoll-core. It's definitely something we will try to achieve soon

**Comment by briot** [comment]
> When splitting gnatcoll in several pieces we thought that some core elements such as traces had direct dependencies on gnatcoll.sql. That's the reason why we kept sql inside gnatcoll-core. It's definitely something we will try to achieve soon

Understood. I think I was relatively careful that optional modules would not depend on
core modules, so it should be safe to move things.

Thanks for the feedback

**Comment by Nikokrock** [comment]
Done
