### ISSUE TITLE
gnattest failure when added gnatcoll.json

### ISSUE THREAD

**Issue by LupusUmbrae** [AdaCore/gnatcoll-core#15]
Hello,

I'm trying to generate tests for some code we've developed but want to use stubs as well. However when I add GNATCOLL.JSON to a file and run `gnattest` with `--stub` I get the following error:

`raised CONSTRAINT_ERROR : gnattest-skeleton-source_table.adb:1023 access check failed`

As a simple test case I took the `simple_stubbing` project from `share/examples/gnattest/` and made the following changes;

`ops.gpr` I added `with "gnatcoll";`

`square.ads` I added a function;

```ada
with GNATCOLL.JSON;

package Square is
   function Square return Integer;
   --  Returns a square of a number

   function Temp return GNATCOLL.JSON.JSON_Value;
end Square;
```

`square.adb` Function body added

```ada
with Input;
with GNATCOLL.JSON;

package body Square is

   function Square return Integer is
      A : Integer := Input.Read_Number;
   begin
      return A * A;
   end Square;

   function Temp return GNATCOLL.JSON.JSON_Value is
      A : GNATCOLL.JSON.JSON_Value;
   begin
      return A;
   end Temp;

end Square;
```

Then I use the following to build and generate the tests;

```bash
$ gprbuild -P ops.gpr 
Compile
   [Ada]          square.adb
$ gnattest ops.gpr --stub -v
gnattest GPL 2017 (20170515)
Copyright 2011-2017, AdaCore.
[0] square.ads
raised CONSTRAINT_ERROR : gnattest-skeleton-source_table.adb:1023 access check failed
```

I installed ada via the `gnat-gpl-2017-x86_64-linux-bin` download, and running on Ubuntu (although the same issue has been seen on SuSE and CentOS).

Can you let me know if I've done something wrong, or if there is a way to resolve this issue with generating stubs? (Such as a way to exclude gnatcoll from the stubbing?)

Thanks,
Robin

**Comment by t-14** [comment]
We can reproduce and will investigate. But note that this is not the right place for this report since it's not a gnatcoll-core problem. You should send a message to report@adacore.com for this issue.

**Comment by LupusUmbrae** [comment]
Thanks for the reply..

First time using Ada so wasn't aware of the report email, and only raised it here as the addition on GNATCOL was causing the problem

**Comment by t-14** [comment]
As far as we can tell, import of any package from an "externally built" project would cause it. We are kinda surprised nobody stumbled upon it until now. We have fixed it, but unfortunately you will have to wait for GNAT GPL 2018 scheduled for later this year to benefit from this. A workaround is to tweak gnatcoll installation process so that the deployed project is not externally built (i.e. don't use gprinstall to deploy it).
