### ISSUE TITLE
Continuous Integration tests fail, may be broken build.

### ISSUE THREAD

**Issue by plestedr** [AdaCore/gnatcoll-core#22]
Continuous integration test are failing with this message:

gnatcoll-projects.adb:4976:23: "Expression" not declared in "Proc"

Is there a way to restart these tests? Will they run again automatically in the future for pull requests that are failing now because of that issue? 

Thanks!
Bob

**Comment by Nikokrock** [comment]
Fixed on Linux

**Comment by Nikokrock** [comment]
And Windows too.

No CI are not rerun automatically for pull requests and the user cannot force them either

**Comment by Nikokrock** [comment]
Fixed
