### ISSUE TITLE
Mustn’t use parallel make to install

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/gnatcoll-core#27]
I used `make -j3 install`, which turns out to be a Bad Idea because the Makefile isn’t set up for that, and the three parallel gprinstall’s end up confusing each other over the manifest.

Could a note to the effect of "don’t specify parallel builds with the `-j` flag" be added? (actually, the build was OK, it was just the install that failed).

**Comment by pmderodat** [comment]
This is now done. Thank you again for having reported this!
