### ISSUE TITLE
Error build gnatcoll-core

### ISSUE THREAD

**Issue by drblez** [AdaCore/gnatcoll-core#28]
I have GNAT 2017
`GNAT GPL 2017 (20170515-63)
Copyright (C) 1996-2017, Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

and fresh clone of gnatcoll-core

when i do make:

PATH="/usr/bin:/usr/local/gnat/bin:$PATH" make

I receive:

gprbuild -p -m --target=x86_64-darwin  -j0 -XGNATCOLL_MMAP=yes -XGNATCOLL_MADVISE=yes -XGNATCOLL_ATOMICS=intrinsic -XGNATCOLL_VERSION=0.0 -XGNATCOLL_OS=osx -XBUILD=PROD  -XLIBRARY_TYPE=static -XXMLADA_BUILD=static -XGPR_BUILD=static \
		-XGNATCOLL_MMAP=yes -XGNATCOLL_MADVISE=yes -XGNATCOLL_ATOMICS=intrinsic -XGNATCOLL_VERSION=0.0 -XGNATCOLL_OS=osx -XBUILD=PROD gnatcoll.gpr
Compile
   [C]            update_path.c
   [C]            terminals.c
   [C]            set_std_prefix.c
   [C]            separate_run_path_option.c
   [C]            run_path_option.c
   [C]            objlist_file.c
   [C]            link_max.c
   [C]            gnatcoll_support.c
   [C]            getrss.c
   [Ada]          gnatcoll-paragraph_filling.adb
   [Ada]          gnatcoll-paragraph_filling-words.adb
   [Ada]          gnatcoll-paragraph_filling-badnesses.adb
   [Ada]          gnatcoll.ads
   [Ada]          gnatcoll-vfs_utils.adb
   [Ada]          gnatcoll-vfs_types.ads
   [Ada]          gnatcoll-vfs.adb
   [Ada]          gnatcoll-utils.adb
   [Ada]          gnatcoll-tribooleans.adb
   [Ada]          gnatcoll-traces.adb
   [Ada]          gnatcoll-terminal.adb
   [Ada]          gnatcoll-templates.adb
   [Ada]          gnatcoll-symbols.adb
   [Ada]          gnatcoll-strings_impl.adb
   [Ada]          gnatcoll-strings.ads
   [Ada]          gnatcoll-storage_pools.ads
   [Ada]          gnatcoll-storage_pools-headers.adb
   [Ada]          gnatcoll-storage_pools-alignment.adb
   [Ada]          gnatcoll-scripts.adb
   [Ada]          gnatcoll-scripts-utils.adb
   [Ada]          gnatcoll-scripts-shell.adb
   [Ada]          gnatcoll-scripts-projects.adb
gnatcoll-projects.adb:3429:24: "String_Vectors" is undefined (more references follow)
gnatcoll-projects.adb:3444:10: invalid prefix in selected component "Mains_Str_List"
gnatcoll-projects.adb:4991:23: "Expression" not declared in "Proc"

   compilation of gnatcoll-scripts-projects.adb failed

gprbuild: *** compilation phase failed
make: *** [build-static] Error 4

**Comment by pmderodat** [comment]
Hello,

It seems that you are compiling the master branch of gnatcoll-core with an old version of libgpr (specifically without this commit: https://github.com/AdaCore/gprbuild/commit/5db0cc91d136e7a4818453e7b2aa3b85045486c2): in this case, the error you get is expected. Unfortunately, this new repository (gnatcoll-core) has been created after the GNAT GPL 2017 release, so there is no corresponding branch. Can you try building & installing the latest libgpr? (https://github.com/AdaCore/gprbuild)

Note that the next GNAT GPL version (GNAT Community 2018, it’s renamed) will be released in the coming weeks, so another option is to wait for it. :-)

**Comment by mosteo** [comment]
I experienced this too a while ago. Depending on what you want from gnatcoll, I have a recent fork stripped of libgpr dependencies here that I've tested with GPL 2017: https://github.com/alire-project/gnatcoll-core/tree/slim
Caveat: I have not used it at all besides a few minimal tests with the Strings package.

**Comment by pmderodat** [comment]
@drblez At this point, we will consider that you have several ways out: either use the GNAT GPL 2017 release of GNATCOLL, either recompile a recent version of `libgpr` to match the recent version of `gnatcoll-core` that you are trying to build. So I’m closing this issue for now, but don’t hesitate to followup if you have further trouble. Thank you in advance!
