### ISSUE TITLE
Unknown project file "gpr" - Error

### ISSUE THREAD

**Issue by mkbbala** [AdaCore/gnatcoll-core#30]
![image](https://user-images.githubusercontent.com/42435498/44201046-ddd08800-a165-11e8-8773-b5a4bb735a97.png)

Any solution for this error?
Getting this error while running "gprbuild gnatcoll.gpr" in windows OS

Also, I don't see any file named "make" in the directory.not sure whether it ll create upon successful building.Any help is appreciated.

**Comment by pmderodat** [comment]
Hello,

What compiler are you using? Is it a GNAT Community release (https://www.adacore.com/download), or a compiler built from sources at the FSF? (for instance http://gnuada.sourceforge.net/). You can tell running: `gprbuild --version`.

There is a `Makefile` file at the root of this repository: I’m not sure what else you would expect. :-)

**Comment by mkbbala** [comment]
C:\Users\bmurugan\Desktop\gnatcoll-core-master>gprbuild --version
GPRBUILD Pro 2.2.2 (20150605) (i686-pc-mingw32)
Copyright (C) 2004-2015, Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
See your AdaCore support agreement for details of warranty and support.
If you do not have a current support agreement, then there is absolutely
no warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.

**Comment by mkbbala** [comment]
I think "make" is a command in Cygwin terminal. Updating now the Cygwin64 setup.

**Comment by pmderodat** [comment]
Ok. It seems that you have a fairly old toolchain: you’ll probably need to update it in order to be able to build GNATCOLL, anyway. Either download a recent GNAT Community release (https://www.adacore.com/download), either try to get an upgrade from your distribution.

`make` is indeed a valid command in Cygwin, but what you will find in this repository is `Makefile`, which is the file that `make` looks for by default. So all should be fine here.

**Comment by mkbbala** [comment]
Thanks for the suggestion.
Downloading recent GNAT Community release.

**Comment by pmderodat** [comment]
Ok. By the way, GNAT Community 2018 ships with GNATCOLL, so you will not need to compile it yourself. :-)

**Comment by mkbbala** [comment]
Ok.. Good News! Thanks!!

**Comment by t-14** [comment]
gprbuild version 2.2.2 is part of our GNAT Enterprise line. If you are a supported user I recommend that you contact customer support for any questions regarding installation and use of our commercial products.
