### ISSUE TITLE
GPRBUILD Pro 2.2.2 - How to use gnatcoll?

### ISSUE THREAD

**Issue by mkbbala** [AdaCore/gnatcoll-core#31]
Getting an error unknown project file: "gnatcoll" in GPRBUILD Pro 2.2.2
![image](https://user-images.githubusercontent.com/42435498/44204007-a0bcc380-a16e-11e8-88dd-84aa17e2c6e4.png)

Do we need any pre-setup to use this package?

reference: https://www.adacore.com/gems/gem-114-logging-with-gnatcoll-traces

**Comment by t-14** [comment]
As I suggested in #30 - for any questions regarding installation and use of our commercial products, can you please contact our support, thanks in advance.

**Comment by mkbbala** [comment]
Thank you! I could able to use the latest version successfully.
I haven't done anything special.It started working when the new bin file path is added in %path%.
Can you please let me know the link for contacting support?

**Comment by t-14** [comment]
If you are a supported user, you should open https://www.adacore.com/login, and enter your login information.
