### ISSUE TITLE
GNATCOLL.JSON very slow parsing of large float values

### ISSUE THREAD

**Issue by touisteur** [AdaCore/gnatcoll-core#4]
Hi,

While trying to pass a JSON test suite (https://github.com/nst/JSONTestSuite/blob/master/test_parsing) on GNATCOLL.JSON, I noticed that the parsing of some of the files, those with "huge" floating point numbers, were very slow to parse with GNATCOLL.JSON.

With the following file : https://github.com/nst/JSONTestSuite/blob/master/test_parsing/i_number_huge_exp.json (and some other number_huge.json files).

And the following test program :

```
procedure JSON_Test is
   Filename  : constant String := Ada.Command_Line.Argument(1);
   JSON_Data : Unbounded_String := File_IO.Read_File (Filename);
begin
   declare
      Value : GNATCOLL.JSON.JSON_Value := GNATCOLL.JSON.Read (Strm     => JSON_Data,
                                                              Filename => Filename);
   begin
      declare
         New_JSON_Data : constant Unbounded_String :=
           GNATCOLL.JSON.Write (Item => Value, Compact => False);
      begin
         File_IO.Write_File (File_Name     => "out.json",
                             File_Contents => New_JSON_Data);
      end;
   end;
end JSON_Test;
```
With the 2016, GPL version of GNATCOLL I compile the program, then run : 

`time json_test input/i_number_huge_exp.json`

I get :
`input/i_number_huge_exp.json:1:2: Numerical value too large to fit into an IEEE 754 float`
(which might be OK, I didn't check for correctness :-))

but then the timing part gives :

```
real    0m7.273s
user    0m3.717s
sys    0m0.008s
```

My machine isn’t fast (a VM in an old PC), but still this is far far longer than other examples from the same test suite.

This is a denial of service waiting to happen.

Just thought you might be interested.

Cheers.
Lionel

**Comment by Nikokrock** [comment]
I will make a check on this one. Though the test is indeed a bit weird the average max double float is around 10^308 and the number of atoms in the universe around 10^82 ;-)

**Comment by Nikokrock** [comment]
Did some analysis on that one. The issue is not in the parsing but in the conversion from string to float in the gnat runtime. So will close this issue as not gnatcoll related.
