### ISSUE TITLE
Error with GNAT 2019 conpile of collections - see #41

### ISSUE THREAD

**Issue by srb623** [AdaCore/gnatcoll-core#42]
I thank the team for the prompt response to #41 and the explanation re the warnings but the answer did not deal with the main issue, that being the error on line 11245 in gnatcoll-projects.adb.  This is the real problem I am having.  I was not overly concerned re the warnings, but mentioned them in case it was helpful.  The error on line 11245 produces the following error message - 

gnatcoll-projects.adb:11245:20: "Free_Knowledge_Base" not declared in "Knowledge"

and it is this that I would appreciate some advice with.

**Comment by t-14** [comment]
Out of 3 options listed in #41, in fact only the first two will work for you: you should either use gnatcoll from GNAT Community, or build a recent libgpr from sources. libgpr API has changed and gnatcoll uses the new API, so you can't use old libgpr with new gnatcoll.
