### ISSUE TITLE
Examples needed for Scripting

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/gnatcoll-core#49]
In the GNATCOLL core documentation, at section 3.2 Scripts API in http://docs.adacore.com/live/wave/gnatcoll-core/html/gnatcoll-core_ug/scripting.html#scripts-api, it says in the 6th para

"GNATColl comes with some examples, which you can use as a reference when building your own application. See the <prefix>/share/examples/gnatcoll directory."

Unfortunately, there are no examples there related to embedding scripts (and I could really do with one!)

**Comment by briot** [comment]
> Unfortunately, there are no examples there related to embedding scripts (and I could really do with one!)


Hi Simon,

There seems to be an `examples/common.adb` file which contains the following
code:

     Repo : Scripts_Repository;
   begin
      --  Register all scripting languages. In practice, you only need to
      --  register those you intend to support

      Repo := new Scripts_Repository_Record;
      Register_Python_Scripting (Repo, "Hello");
      Register_Standard_Classes (Repo, "Console");

      --  Now register our custom functions. Note that we do not need to
      --  register them once for every support language, once is enough, they
      --  are automatically exported to all registered languages.

      --  Available as "Hello.hello("world")" in python,
      --  and "hello world" in shell script
      Register_Command
        (Repo, "hello", 0, 1,
         Handler => On_Hello'Unrestricted_Access);


I did not check whether it still compiles, but this is the general idea of embedding python:
you create a scripts repository, in which you explicitly register python as a scripting
language (at this stage, ignore the “gnatcoll shell” script, it is worthless and was really
only useful at the very beginning.

You can then add custom commands and classes, with Ada callbacks for them.

The difficult part (not shown in the example above) is to provide some sort of console
in which users can interact with python (depending on your application, this might not
be useful either).
For this, take a look at the other files in the same `examples` directory. Start with
`newclass.adb` which has a misleading name nowadays. It binds python’s stdin and
stdout to a custom Console object, then executes the command typed by the user.

I haven’t used this in three years, but I think this should get you started. Do not hesitate
to followup if you have further questions, I’ll see if I can remember any of this.

Manu

**Comment by simonjwright** [comment]
Manu,

There indeed used to be a directory as you describe in the old GNATCOLL; I found it in my GCC 4.8.1 distribution for macOS! (2013).
Also in GNAT CE 2019, only text consoles.
GNAT CE 2017 has some GTK examples.

**Comment by briot** [comment]
> There indeed used to be a directory as you describe in the old GNATCOLL; I found it in my GCC 4.8.1 distribution for macOS! (2013).
> Also in GNAT CE 2019, only text consoles.
> GNAT CE 2017 has some GTK examples.

I was checking on github, in an old fork of mine (https://github.com/briot/gnatcoll-core/tree/master/examples)
but indeed it is gone from master in AdaCore. Sorry I forgot to check there.
I’ll let the AdaCore people followup on why they removed those examples (as badly organized as they were,
they did provide initial examples)

**Comment by t-14** [comment]
Hi Simon,

We are adding examples as time permits. In the meantime, there is a test for scripts in testsuite/tests/scripts/completion that can serve as a sort of an example.

Manu,

> I’ll let the AdaCore people followup on why they removed those examples (as badly organized as they were,
they did provide initial examples)

None of the old examples work with gnatcoll-core only, they'd be more at home in gnatcoll-bindings project where python module resides, but unfortunately, we didn't yet have time to set up the examples there.

If either of you is motivated to adapt the old examples in a way that will remove the python dependency - don't hesitate to submit a PR, we will be happy to push it through. Of course, this is also true for any other example you feel like contributing.
