### ISSUE TITLE
GNATCOLL.JSON unexpected crash : ADA.STRINGS.INDEX_ERROR : a-strunb.adb:1482

### ISSUE THREAD

**Issue by touisteur** [AdaCore/gnatcoll-core#5]
Hi,

While trying to pass a JSON test suite (https://github.com/nst/JSONTestSuite/blob/master/test_parsing) on GNATCOLL.JSON, I noticed that some of the files, when parsed, gave exceptions different from the "excepted" GNATCOLL.JSON.INVALID_JSON_STREAM.

The following test cases crash with the exception:
- n_string_1_surrogate_then_escape_u1.json
- n_string_1_surrogate_then_escape_u.json
- n_string_invalid-utf-8-in-escape.json
- n_structure_unclosed_array_partial_null.json
- n_structure_unclosed_array_unfinished_false.json
- n_structure_unclosed_array_unfinished_true.json

with the following test program:

```
procedure JSON_Test is
   Filename  : constant String := Ada.Command_Line.Argument(1);
   JSON_Data : Unbounded_String := File_IO.Read_File (Filename);
begin
   declare
      Value : GNATCOLL.JSON.JSON_Value := GNATCOLL.JSON.Read (Strm     => JSON_Data,
                                                              Filename => Filename);
   begin
      declare
         New_JSON_Data : constant Unbounded_String :=
           GNATCOLL.JSON.Write (Item => Value, Compact => False);
      begin
         File_IO.Write_File (File_Name     => "out.json",
                             File_Contents => New_JSON_Data);
      end;
   end;
end JSON_Test;
```
With the 2016, GPL version of GNATCOLL.

BR
Lionel

**Comment by Nikokrock** [comment]
Thanks for reporting this issue. we will take a look at it

**Comment by Nikokrock** [comment]
Good exception now raised
