### ISSUE TITLE
XMLAda dependency is not listed in gnatcoll.gpr

### ISSUE THREAD

**Issue by LordAro** [AdaCore/gnatcoll-core#51]
When compiling with `--no-indirect-imports`, this results in:

```
Unit "gnatcoll.projects" cannot import unit "dom":
  "GnatColl" does not directly import project "XmlAda_Dom"
Unit "gnatcoll.projects" cannot import unit "dom.core":
  "GnatColl" does not directly import project "XmlAda_Dom"
Unit "gnatcoll.projects" cannot import unit "dom.core.documents":
  "GnatColl" does not directly import project "XmlAda_Dom"
Unit "gnatcoll.projects" cannot import unit "dom.core.nodes":
  "GnatColl" does not directly import project "XmlAda_Dom"
Unit "gnatcoll.projects" cannot import unit "input_sources":
  "GnatColl" does not directly import project "XmlAda_Input"
Unit "gnatcoll.projects" cannot import unit "input_sources.file":
  "GnatColl" does not directly import project "XmlAda_Input"
Unit "gnatcoll.projects" cannot import unit "sax":
  "GnatColl" does not directly import project "XmlAda_Sax"
Unit "gnatcoll.projects" cannot import unit "sax.readers":
  "GnatColl" does not directly import project "XmlAda_Sax"
Unit "gnatcoll.projects" cannot import unit "schema":
  "GnatColl" does not directly import project "XmlAda_Schema"
Unit "gnatcoll.projects" cannot import unit "schema.dom_readers":
  "GnatColl" does not directly import project "XmlAda_Schema"
gprbuild: *** compilation phase failed
```

Should be easy fix... :)

**Comment by anisimkov** [comment]
Why do you need --no-indirect-imports option ?

**Comment by LordAro** [comment]
We have an extremely large Ada project with various libraries intertwined. I find it useful to help track what library actually uses which other.

**Comment by anisimkov** [comment]
Maybe you better build and install gnatcoll-core first and then use this switch for your projects ?

**Comment by LordAro** [comment]
Ideally... but we also have to make our own modifications to gnatcoll (don't ask), so it all gets built all at once. Obviously it's not difficult to add some more lines to the gpr file... it would just be nice not to have to.

**Comment by briot** [comment]
> Ideally... but we also have to make our own modifications to gnatcoll (don't ask), so it all gets built all at once. Obviously it's not difficult to add some more lines to the gpr file... it would just be nice not to have to.

Former maintainer of gnatcoll here,

Actually, I would be interested to know which modifications you have to do to GNATCOLL. We also have a large number of those local changes (to the point that some of them are actually backward incompatible especially in the SQL support). Would be nice to know if you hit the same issues…

Emmanuel

**Comment by LordAro** [comment]
They're mostly centred around GNATCOLL.Projects. It's not quite flexible enough for what we do with them, and other limitations (like not being able to modify aggregate projects) get in the way

**Comment by Fabien-Chouteau** [comment]
> Ideally... but we also have to make our own modifications to gnatcoll (don't ask), so it all gets built all at once.

Hi @LordAro, I think the main point here is that `--no-indirect-imports` is not part of our (AdaCore) build flags, and there is no plan to change that. Therefore even if we use direct imports for the case you mention there is no guaranty for you that this problem won't come back. It is better for you to find a way to build your `gnatcoll` fork with a procedure that matches ours, i.e. build and install `gnatcoll` separately from your application. Alternatively, since you already have a fork, you can use direct imports in your version.
