### ISSUE TITLE
"Get_Lower_Name_Id" is undefined error when building

### ISSUE THREAD

**Issue by AwesomeBiscuitBadger** [AdaCore/gnatcoll-core#52]
Am building with the latest GNAT GPL for Ubuntu, running on 20.04LTS.

This is the error I get after the build process has built a number of packages.

Hopefully this is a noddy error -- what's the solution? I've grepped my GNAT install source and there is no occurrence of "Get_Lower_Name_Id" in there. Do I need to have GNAT Pro to use this? As I don't have it (and won't be getting it) is there a commit hash that works with the GPL version?

**Comment by anisimkov** [comment]
Could you provide exact error message ?

**Comment by anisimkov** [comment]
I guess you are trying to build fresh sources of gnatcoll-core, right ?
If so you should rebuild libgpr first. It is in gprbuild repository.
You should
make libgpr.build
make libgpr.install

**Comment by AwesomeBiscuitBadger** [comment]
Thanks, this fixed my issue.
