### ISSUE TITLE
Error handling in GNATCOLL.JSON

### ISSUE THREAD

**Issue by forsyth** [AdaCore/gnatcoll-core#53]
The Read function raises Invalid_JSON_Stream on a format error or empty file, but also prints a diagnostic on standard output which might not be desired by an application.
Only that diagnostic includes the line and column numbers: the text attached to the exception discards it.

 ```
        Ada.Text_IO.Put_Line (Format_Parsing_Error (Result.Error));
         raise Invalid_JSON_Stream with To_String (Result.Error.Message);
```

**Comment by pmderodat** [comment]
Hello @forsyth,

What you describe looks legitimate: the Read function overload that returns a `Read_Result` value does not raise an exception and does not print anything on standard output. `Read_Result` contains both the error message and location information (line and column numbers), and indeed `To_String (Result.Error.Message)` doesn’t include location info… but that’s precisely what `Format_Parsing_Error` is for (include that info).

So I don’t understand what is the purpose of this issue: could you clarify what you tried, show the output you get, and specify what exact output you would like to get? Thanks!

**Comment by forsyth** [comment]
I see the confusion now. It was my fault for not comparing the version I was using (19.x) and the current version (20.x): the Read_Result and associated overloaded Read were not in the gnatcoll-json.ads I was using, only in the body, and thus not accessible. I can see where the change was made. Luckily I can simply switch to the newer version.
