### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by bracke** [AdaCore/gnatcoll-core#55]
Hi

I'm getting a build error when trying to build GNATCOLL-core on Ubuntu with GNAT Community 2020:

> gnatcoll-arg_lists.adb: 467:36: no selector "Append_Vector" for private type "Ada.Containers.Vectors.Vector" from instance at GNATCOLL-arg-lists.ads:160
> compilation of GNATCOLL-arg_lists.adb failed

Looks like the Travis build on this site also fails with the same error.
[https://travis-ci.org/github/AdaCore/gnatcoll-core](https://travis-ci.org/github/AdaCore/gnatcoll-core)

Kind regards
Bent Bracke

**Comment by t-14** [comment]
Hi Bent, can you please switch to Community 2021? There has been an incompatible change.

> Looks like the Travis build on this site also fails with the same error.

Thanks for the heads up.

**Comment by steve-cs** [comment]
FYI.  travis-ci.org finally closed shop on June 15.  It doesn't build anything any more.

**Comment by bracke** [comment]
Thanks for the response.  I will switch to 2021 :-)
