### ISSUE TITLE
GNATCOLL.JSON unexpected crash : CONSTRAINT_ERROR : bad input for 'Value: "16#??????"]#"

### ISSUE THREAD

**Issue by touisteur** [AdaCore/gnatcoll-core#6]
Hi,

While trying to pass a JSON test suite (https://github.com/nst/JSONTestSuite/blob/master/test_parsing) on GNATCOLL.JSON, I noticed that some of the files, when parsed, gave exceptions different from the "excepted" GNATCOLL.JSON.INVALID_JSON_STREAM.

The following test cases crash with the exception (in the title):
- n_string_1_surrogate_then_escape_u1x.json
- n_string_incomplete_escaped_character.json
- n_string_incomplete_surrogate.json

with the following test program:

```
procedure JSON_Test is
   Filename  : constant String := Ada.Command_Line.Argument(1);
   JSON_Data : Unbounded_String := File_IO.Read_File (Filename);
begin
   declare
      Value : GNATCOLL.JSON.JSON_Value := GNATCOLL.JSON.Read (Strm     => JSON_Data,
                                                              Filename => Filename);
   begin
      declare
         New_JSON_Data : constant Unbounded_String :=
           GNATCOLL.JSON.Write (Item => Value, Compact => False);
      begin
         File_IO.Write_File (File_Name     => "out.json",
                             File_Contents => New_JSON_Data);
      end;
   end;
end JSON_Test;
```
With the 2016, GPL version of GNATCOLL.

BR
Lionel

**Comment by Nikokrock** [comment]
Good exception is now raised
