### ISSUE TITLE
Unable to build -- apparent circular dependency

### ISSUE THREAD

**Issue by byu9** [AdaCore/gnatcoll-core#60]
Hi,
There is an apparent circular dependency during build
* `gnatcoll-core` depends on `gpr`
* `gpr` depends on `gnatcoll_iconv`, `gnatcoll_gmp`, `langkit_support`, and `libadalang`
*  `libadalang` depends on `gnatcoll-core`.

#### The details are as follows

When attempting to build `gnatcoll-core` on Debian Linux with `gnat 10.2.1` and `gprbuild Pro 18.0w`, dependency is not met on `gpr`

```
# ~/Downloads/gnatcoll-core-20.2
make

...
gnatcoll.gpr:24:06: imported project file "gpr" not found
gprbuild: "gnatcoll.gpr" processing failed
make: *** [Makefile:128: build-static] Error 4
```

However, when building `gpr`, a dependency is not met on `gnatcoll_iconv`, `gnatcoll_gmp`, `langkit_support`, and `libadalang`.

```
# ~/Downloads/gpr-20.2
make
...
gpr2.gpr:19:06: imported project file "gnatcoll_iconv" not found
gpr2.gpr:20:06: imported project file "gnatcoll_gmp" not found
gpr2.gpr:21:06: imported project file "langkit_support" not found
gpr2.gpr:22:06: imported project file "libadalang" not found
gprbuild: "gpr2.gpr" processing failed
make: *** [Makefile:104: build-static] Error 4
```

However, when building `libadalang`, a dependency is not met on `gnatcoll-core`

In `~/Downloads/libadalang-20.2/user_manual/building.rst`:

> * Build and install the GNATcoll library (core, plus Iconv and GMP bindings).
  You can find its source release on `AdaCore's website
  <https://www.adacore.com/download>`_ or directly on GitHub's repositories for
  `gnatcoll-core <https://github.com/AdaCore/gnatcoll-core>`_ and
  `gnatcoll-bindings <https://github.com/AdaCore/gnatcoll-bindings>`_. Just
  make sure you checkout the ``gpl-20**`` branch corresponding to your GNAT
  Community release.

**Comment by t-14** [comment]
Hi,

I think you are confusing names of gpr files with names of gh projects they come from. "gpr.gpr" is coming from project "gprbuild", not from project "gpr" (the latter provides gpr2.gpr)

**Comment by byu9** [comment]
OK That makes sense. Thanks.

**Comment by bib1963** [comment]
To AdaCore - please update the README.md file to tell everyone this. It is not clear at all.

**Comment by tkacvins** [comment]
This is not solved for me.  I get this error

```
gprbuild -p -m --target=x86_64-linux  -j0 -XGNATCOLL_MMAP=yes -XGNATCOLL_MADVISE=yes -XGNATCOLL_VERSION=0.0 -XGNATCOLL_OS=unix -XBUILD=PROD   -XLIBRARY_TYPE=static -XXMLADA_BUILD=static -XGPR_BUILD=static \
        -XGNATCOLL_MMAP=yes -XGNATCOLL_MADVISE=yes -XGNATCOLL_VERSION=0.0 -XGNATCOLL_OS=unix -XBUILD=PROD gnatcoll.gpr -v

==============Messages for file: /home/LOCAL/vapkay/gnatcoll-core/gnatcoll.gpr

    24. with "gpr";
             |
        >>> imported project file "gpr" not found
gprbuild: "gnatcoll.gpr" processing failed
```

even thought I have `gprbuild` installed.  I am using the GNAT tool chain from GCC 12.1.0 (built from source) and `gprbuild` and `gnatcoll` GitHub projects, each at tag `v24.0.0`.

For `gprbuild`, I had to bootstrap `gprbuild` and also install `xmlada` per the build instructions.  I followed the build instructions (and this issue), but even though `gprbuild` is installed, I cannot find `gpr.gpr`, or at least not anything that I could use in `ADA_PROJECT_PATH`

**Comment by bib1963** [comment]
> This is not solved for me. I get this error
> 
> ```
> gprbuild -p -m --target=x86_64-linux  -j0 -XGNATCOLL_MMAP=yes -XGNATCOLL_MADVISE=yes -XGNATCOLL_VERSION=0.0 -XGNATCOLL_OS=unix -XBUILD=PROD   -XLIBRARY_TYPE=static -XXMLADA_BUILD=static -XGPR_BUILD=static \
>         -XGNATCOLL_MMAP=yes -XGNATCOLL_MADVISE=yes -XGNATCOLL_VERSION=0.0 -XGNATCOLL_OS=unix -XBUILD=PROD gnatcoll.gpr -v
> 
> ==============Messages for file: /home/LOCAL/vapkay/gnatcoll-core/gnatcoll.gpr
> 
>     24. with "gpr";
>              |
>         >>> imported project file "gpr" not found
> gprbuild: "gnatcoll.gpr" processing failed
> ```
> 
> even thought I have `gprbuild` installed. I am using the GNAT tool chain from GCC 12.1.0 (built from source) and `gprbuild` and `gnatcoll` GitHub projects, each at tag `v24.0.0`.
> 
> For `gprbuild`, I had to bootstrap `gprbuild` and also install `xmlada` per the build instructions. I followed the build instructions (and this issue), but even though `gprbuild` is installed, I cannot find `gpr.gpr`, or at least not anything that I could use in `ADA_PROJECT_PATH`

If you installed gprbuild from source, then in the gprbuild directory, there is a directory called `gpr` , just cd into it & run `gprbuild/gprinstall` etc.

**Comment by tkacvins** [comment]
OK, so I ran `gprbuild` and `gprinstall` in the `gprbuild` repo's `gpr` subdirectory and set `ADA_PROJECT_PATH` to include the install location of `gpr.gpr`.  Now I get this

```
gprbuild -p -m --target=x86_64-linux  -j0 -XGNATCOLL_MMAP=yes -XGNATCOLL_MADVISE=yes -XGNATCOLL_VERSION=0.0 -XGNATCOLL_OS=unix -XBUILD=PROD   -XLIBRARY_TYPE=static -XXMLADA_BUILD=static -XGPR_BUILD=static  -XGNATCOLL_MMAP=yes -XGNATCOLL_MADVISE=yes -XGNATCOLL_VERSION=0.0 -XGNATCOLL_OS=unix -XBUILD=PROD gnatcoll.gpr -v

==============Messages for file: /home/BUILD64/bin/gprbuild/share/gpr/gpr.gpr

    11.    BUILD : BUILD_KIND := external("GPR_BUILD", "default");

        >>> value "static" is illegal for typed string "build"

gprbuild: "gnatcoll.gpr" processing failed
```

Something is not quite right with this but I am out ideas as to where to look

**Comment by bib1963** [comment]
Ugh, sorry, gave wrong info. From the top level Makefile, it says to run `make libgpr.build` & `make libgpr.install`. That will build the 3 types of libs, relocatable, static & static-pic. Yup, really not well documented.

**Comment by tkacvins** [comment]
Ah, thank you very much.  That did the trick!

**Comment by bib1963** [comment]
> Ah, thank you very much. That did the trick!

Horrible.... isn't it....

**Comment by t-14** [comment]
FWIW, we've just added a line in the gprbuild project readme mentioning the right make targets.

**Comment by bib1963** [comment]
> FWIW, we've just added a line in the gprbuild project readme mentioning the right make targets.

Since that component is required and non-optional, when someone runs `make`, then gpr should also be automatically be built. It should not be a separate process step. The same goes with installing it.

**Comment by bib1963** [comment]
> This statement is manifestly wrong, this component is perfectly optional and is in fact unused if all one needs to build is the executables; and it's as intended (and if you think about it can't be otherwise, given you need gprbuild to build this component, and it might not exist before you build it... chicken and egg, aka _bootstrapping_...)

And yet, I've never been able to get a runnable system without it being installed due to so much additional components requiring it.
