### ISSUE TITLE
CONSTRAINT_ERROR : gnatcoll-projects.adb:5729 index check failed

### ISSUE THREAD

**Issue by kevlar700** [AdaCore/gnatcoll-core#64]
When using GNAT Studio 23.0w (20220512) to load the project file at the bottom. I get the following log output.
<pre>
   [GPS.KERNEL.TIMEOUT] Starting the program /home/kc/.config/alire/cache/dependencies/gnat_arm_elf_11.2.4_ba16d45c/bin/arm-eabi-gnat 
   [GPS.KERNEL.TIMEOUT] Connect the command_handler to the console 
   [GPS.KERNEL.TIMEOUT] Spawn the process /home/kc/.config/alire/cache/dependencies/gnat_arm_elf_11.2.4_ba16d45c/bin/arm-eabi-gnat 
   [GPS.KERNEL.REMOTE] Spawning 
   [GPS.KERNEL.REMOTE] Arg: "/home/kc/.config/alire/cache/dependencies/gnat_arm_elf_11.2.4_ba16d45c/bin/arm-eabi-gnat" 
   [GPS.KERNEL.REMOTE] Arg: "make" 
   [GPS.KERNEL.REMOTE] Arg: "-h" 
   [GPS.MAIN.WINDOW] Default size for project-props from properties 
   [GPS.KERNEL.TASK.EXCEPTIONS] Unexpected exception: raised CONSTRAINT_ERROR : gnatcoll-projects.adb:5729 index check failed
   _GPS.KERNEL.TASK.EXCEPTIONS_ [/usr/local/GNAT/CR/bin/../lib/gnatstudio/libgnatcoll.so.23.0w]
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c7a179c1 gnatcoll__projects__compute_scenario_variables__register_untyped_var.1798.constprop.0 at ???
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c7a17d06 gnatcoll__projects__compute_scenario_variables__register_var.1778 at ???
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c7a238c7 gnatcoll__projects__for_each_external_variable_declaration at ???
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c7a26235 gnatcoll__projects__compute_scenario_variables at ???
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c7a271aa gnatcoll__projects__scenario_variables__3.part.0 at ???
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c7a27319 gnatcoll__projects__scenario_variables at ???
   _GPS.KERNEL.TASK.EXCEPTIONS_ [/usr/local/GNAT/CR/bin/gnatstudio_exe]
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x4b30826
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x4b30f30
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x4b310eb
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x4bbc4c6
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x4bbfc12
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x405c544
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x405c988
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x405cb06
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x405daf8
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x40a8c2a
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x4053da9
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x4056e3a
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x3f5bf8e
   _GPS.KERNEL.TASK.EXCEPTIONS_ [/usr/local/GNAT/CR/bin/../lib/gnatstudio/libgtkada.so.23.0w]
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c4cfd90f
   _GPS.KERNEL.TASK.EXCEPTIONS_ [/usr/local/GNAT/CR/bin/../lib/gnatstudio/libgobject-2.0.so.0]
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c1014050 g_closure_invoke at gclosure.c:810
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c1025c24 signal_emit_unlocked_R at gsignal.c:3738
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c102c007 g_signal_emit_valist at gsignal.c:3494
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c102c530 g_signal_emit at gsignal.c:3550
   _GPS.KERNEL.TASK.EXCEPTIONS_ [/usr/local/GNAT/CR/bin/../lib/gnatstudio/libgtk-3.so.0]
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c3d6ce72 gtk_widget_activate at gtkwidget.c:7845
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c3c25194 gtk_menu_shell_activate_item at gtkmenushell.c:1375
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c3c2549f gtk_menu_shell_button_release at gtkmenushell.c:791
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c3a9ba1a _gtk_marshal_BOOLEAN__BOXEDv at gtkmarshalers.c:130
   _GPS.KERNEL.TASK.EXCEPTIONS_ [/usr/local/GNAT/CR/bin/../lib/gnatstudio/libgobject-2.0.so.0]
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c101429d _g_closure_invoke_va at gclosure.c:873
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c102b6ea g_signal_emit_valist at gsignal.c:3403
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c102c530 g_signal_emit at gsignal.c:3550
   _GPS.KERNEL.TASK.EXCEPTIONS_ [/usr/local/GNAT/CR/bin/../lib/gnatstudio/libgtk-3.so.0]
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c3d6a632 gtk_widget_event_internal.part.0 at gtkwidget.c:7812
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c3c0d55e propagate_event at gtkmain.c:2588
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c3c0ef21 gtk_main_do_event at gtkmain.c:1921
   _GPS.KERNEL.TASK.EXCEPTIONS_ [/usr/local/GNAT/CR/bin/../lib/gnatstudio/libgdk-3.so.0]
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c3631433 _gdk_event_emit at gdkevents.c:73
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c3666590 gdk_event_source_dispatch at gdkeventsource.c:367
   _GPS.KERNEL.TASK.EXCEPTIONS_ [/usr/local/GNAT/CR/bin/../lib/gnatstudio/libglib-2.0.so.0]
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c0c52b49 g_main_context_dispatch at gmain.c:3325
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c0c52db6 g_main_context_iterate.constprop.0 at gmain.c:4119
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c0c52e5d g_main_context_iteration at gmain.c:4184
   _GPS.KERNEL.TASK.EXCEPTIONS_ [/usr/local/GNAT/CR/bin/../lib/gnatstudio/libgio-2.0.so.0]
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c14e0293 g_application_run at gapplication.c:2559
   _GPS.KERNEL.TASK.EXCEPTIONS_ [/usr/local/GNAT/CR/bin/gnatstudio_exe]
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x2bc669d
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x2b9d9d4
   _GPS.KERNEL.TASK.EXCEPTIONS_ [/lib64/libc.so.6]
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c8e32208
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x7f92c8e322ba
   _GPS.KERNEL.TASK.EXCEPTIONS_ [/usr/local/GNAT/CR/bin/gnatstudio_exe]
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0x2ba8cc3
   _GPS.KERNEL.TASK.EXCEPTIONS_ 0xfffffffffffffffe 
</pre>

<pre>
with "config/stm32l4r9_hal_config.gpr";
project Stm32l4r9_Hal is

   for Library_Name use "Stm32l4r9_Hal";
   for Library_Version use Project'Library_Name & ".so." & Stm32l4r9_Hal_Config.Crate_Version;

   for Source_Dirs use ("src",
                        "src/cortex_m",
                        "src/cortex_m/cm4f",
                        "src/drivers/**",
                        "src/devices/STM32L4R9",
                        "src/svd/STM32L4R9");

   for Object_Dir use "obj";
   for Create_Missing_Dirs use "True";
   for Library_Dir use "lib";
   
      -- Added Manually
   for Target use "arm-eabi";
   for Runtime ("ada") use "zfp-cortex-m4f";
   -- End Added Manually

--   type Library_Type_Type is ("relocatable", "static", "static-pic");
--   Library_Type : Library_Type_Type :=
--    external ("STM32L4R9_HAL_LIBRARY_TYPE", external ("LIBRARY_TYPE", "static"));

   for Library_Kind use "static";
   
 package Compiler is
      for Default_Switches ("ada") use ("-g", "-gnatQ", "-fcallgraph-info=su,da", "-gnato", "-gnatVa", "-gnatwYa.b.fh.h.kl.o.st.w.y.X", "-gnatyaAbBdeiklM120nOrsSu"); -- Don't quit. Generate
      for Local_Configuration_Pragmas use "gnat.adc";
   end Compiler;

   package Binder is
      for Switches ("Ada") use ("-Es"); --  Symbolic traceback
   end Binder;

   package Ide is
      for Vcs_Kind use "git";
      for Vcs_Repository_Root use ".";
   end Ide;

   package Pretty_Printer is
      for Default_Switches ("ada") use ("--call-threshold=1", "--par-threshold=1", "--vertical-enum-types", "--vertical-named-aggregates", "--comments-unchanged", "-W8");
   end Pretty_Printer;

   package Builder is
      for Switches ("ada") use ("-g", "-j2");
   end Builder;

end Stm32l4r9_Hal;
</pre>

**Comment by kevlar700** [comment]
I just had the same exception happen on a newly alr init --bin project.
I am now wondering if it is an issue with python. 
I am running python 3.10.5?

**Comment by t-14** [comment]
We would need a reproducer outside of GNAT Studio context to be able to investigate, so I'll close this one and keep https://github.com/AdaCore/gnatstudio/issues/128 instead.
