### ISSUE TITLE
gnatcoll make fails with undefined Get_Lower_Name_Id

### ISSUE THREAD

**Issue by rogermc2** [AdaCore/gnatcoll-core#66]
gcc-12.1.0
make fails with
`gnatcoll-projects-normalize.adb:1710:19: error: "Get_Lower_Name_Id" is undefined`

**Comment by rogermc2** [comment]
Problem solved

**Comment by rogermc2** [comment]
Problem solved

**Comment by rogermc2** [comment]
Closed

**Comment by Fabien-Chouteau** [comment]
Hello @rogermc2, if you can share here what the issue was it might help other people who find themselves in the same situation.

**Comment by rogermc2** [comment]
The problem was that I had an older version of the package that "Get_Lower_Name_Id" is first declared in.
