### ISSUE TITLE
How to use Python3 with gnatcoll-core?

### ISSUE THREAD

**Issue by rogermc2** [AdaCore/gnatcoll-core#69]
I can't figure out how to add Python3 functionality to `gnatcoll-core`.
Attempts to get `gnatcoll_python3` result in:
~~~                 
Roger@Rogers-Mac-mini alire % alr get gnatcoll_python3 
error: Release within the requested versions [gnatcoll_python3*] does not exist in the catalog.
~~~
Similarly for ` get gnatcoll_python`

**Comment by Fabien-Chouteau** [comment]
Hi @rogermc2 ,

As Simon said on [comp.lang.ada](https://groups.google.com/u/1/g/comp.lang.ada/c/WuLoJ5DY50s) the Alire `gnatcoll_python3` crate is unfortunately not yet supported on macOS. We hope to have it in the next release of Alire.
