### ISSUE TITLE
Improve readability by simplifying boolean expression

### ISSUE THREAD

**Issue by pjljvandelaar** [AdaCore/gnatcoll-core#71]
Dear GnatColl developers,

Why not replace https://github.com/AdaCore/gnatcoll-core/blob/c7abf67e7685734be8f88334f0d0ba409cf8ea1a/src/gnatcoll-vfs.adb#L1632
with
```
if Is_Directory (New_Dir) then
```

Greetings,
 Pierre

Problem detected and solved by Rejuvenation-Ada crate
[![vote for Rejuvenation-Ada as The 2022 Ada Crate Of The Year](https://user-images.githubusercontent.com/18348654/191469254-1ca1f4a0-6242-43fa-94a2-f39f55817fdc.jpg)](https://github.com/AdaCore/Ada-SPARK-Crate-Of-The-Year/issues/15)

**Comment by t-14** [comment]
Thank you for the suggestion, we have cleaned it up. The blurb is a bit gushing though given we are talking of one instance of "if True", don't you think?
