### ISSUE TITLE
No option to extend a sequence with an existing field

### ISSUE THREAD

**Issue by jildert17** [AdaCore/gnatcoll-core#77]
I cannot find the option to extend a JSON object with an existing object, e.g.:

`Data : JSON_Value := Read ("{"key1":"value1","key2":"value2"}");`
`New_Field : JSON_Value := Read  ("{"key3":"value3"}");`
`Data.Extend (New_Field)`

Such that the resulting value is: {"key1":"value1","key2":"value2","key3":"value3"}

The reason I want it is because I want to have functions creating JSON objects, and later on call these functions to build a sequence of fields.

**Comment by Jicquel** [comment]
Hello @jildert17, thank you for opening up this issue. This feature is indeed not supported by gnatcoll-core. If you still need it, you can either contribute to the project or wait for us to implement it. The latter may take time, as this is not a high priority task.

**Comment by Jicquel** [comment]
In the meantime we are closing this issue, but we take note of your interest and will keep it in mind. Feel free to reopen this issue if needed.
