### ISSUE TITLE
GNATCOLL.CONFIG crash on fuzzing (gnatcoll-templates.adb:173:39 index check failed)

### ISSUE THREAD

**Issue by touisteur** [AdaCore/gnatcoll-core#8]
Hi,

I'm fuzzing GNATCOLL GPL 2016 (sorry @t-14 I had everything already set up...) and GNATCOLL.CONFIG gives me a CONSTRAINT_ERROR: gnatcoll-templates.adb:173:39 index check failed on the files uploaded there : [gnatcoll-templates-adb-173-39.zip](https://github.com/AdaCore/gnatcoll-core/files/1503449/gnatcoll-templates-adb-173-39.zip).

I'm not saying it's a problem, just an issue found through fuzz testing. Might be excepted behaviour for GNATCOLL.CONFIG (and in that case, you're welcome to close the issue).

The test program I use is the simplest I could muster in 5 minutes : 

```
with GNATCOLL.Config;  use GNATCOLL.Config;
with Ada.Text_IO;      use Ada.Text_IO;

with Ada.Exceptions;
with GNAT.Exception_Actions;

with Ada.Command_Line;

procedure Run is
   Ini  : INI_Parser;
   Pool : Config_Pool;
   Filename : constant String := Ada.Command_Line.Argument (1);
begin
   Open (Ini, Filename);
   Fill (Pool, Ini);
exception -- all this needed to inform afl-fuzz that we had a "crash"
   when Occurence : others =>
      Ada.Text_IO.Put_Line ("exception occured for " & Filename & " [" & Ada.Exceptions.Exception_Name (Occurence) & "] [" & Ada.Exceptions.Exception_Message (Occurence) & "] [" & Ada.Exceptions.Exception_Information (Occurence) & "]");
      GNAT.Exception_Actions.Core_Dump (Occurence);
end Run;
```

**Comment by t-14** [comment]
> sorry @t-14 I had everything already set up...

It's good you have everything set up, but I think you should pause and consider in which cases fuzz testing is useful and in which it is not. Unless the structured input is expected to cross trust boundary - it's not, and I don't see how GNATCOLL.CONFIG can end up dealing with config files like that unless the computer is exposed to hard radiation :)

**Comment by touisteur** [comment]
Hi @t-14,

I'm not sure I agree :-). Config files are, in some software, user-provided inputs. They can be corrupted on-disk, during network transfer, in memory and other places. 

Any software with file-based input is worth fuzzing, it allows to find bugs, sometimes interesting, sometimes not. It increases test coverage, even of the stupid stuff.

You think those ones are not likely to be produced by people, fine. But maybe your users allow editing of config files via a web interface or other, maybe they allow users to provide their own configuration files. Maybe they use GNATCOLL.CONFIG for parameters or mission-critical applications (PDI).

Hard radiation is not the only corruption possibility. These files might be transferred through (not so reliable) networks, on (not so reliable) hard drives, through (not ECC checked... and not so reliable) memory. All the checksums might fail, and then you're stuck with a validating parser.

I'm not saying it's the most pressing issue, and you're (of course) free to triage it as low-priority as you want, or close the issue if it can't be reproduced on a recent version or if it's not something you're interested in. I saw a problem, I reported it, the rest is up to you.

Cheers, Vasiliy.

**Comment by t-14** [comment]
> I'm not saying it's the most pressing issue, and you're (of course) free to triage it as low-priority as you want, or close the issue if it can't be reproduced on a recent version or if it's not something you're interested in.

Fair enough. This does reproduce with a recent version so we will keep this open and try to get to fixing it sometime after we are done with more pressing things but before a high energy particle from outer space has the chance to produce this in the wild ;)

**Comment by Nikokrock** [comment]
Fuzz tests you submitted are now passing
