### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by fastrgv** [AdaCore/gnatcoll-core#80]
I built, without issue, the fork for alire-project/gnatcoll-core.
But I cannot build this. Here is the message:

gnatcoll.gpr:24:06: imported project file "gpr" not found
gprbuild: "gnatcoll.gpr" processing failed

**Comment by KhazAkar** [comment]
I also hit the same issue. Either that, or:
```
gprinstall -p -f --target=x86_64-linux -XGNATCOLL_MMAP=yes -XGNATCOLL_MADVISE=yes -XGNATCOLL_BLAKE3_ARCH=x86_64-linux -XGNATCOLL_XXHASH_ARCH=x86_64 -XGNATCOLL_PROJECTS=yes -XGNATCOLL_VERSION=0.0 -XGNATCOLL_OS=unix -XBUILD=PROD  --prefix=/usr/bin/.. -XLIBRARY_TYPE=static -XXMLADA_BUILD=static -XGPR_BUILD=static \
        --build-name=static -XGNATCOLL_MMAP=yes -XGNATCOLL_MADVISE=yes -XGNATCOLL_BLAKE3_ARCH=x86_64-linux -XGNATCOLL_XXHASH_ARCH=x86_64 -XGNATCOLL_PROJECTS=yes -XGNATCOLL_VERSION=0.0 -XGNATCOLL_OS=unix -XBUILD=PROD \
         --sources-subdir=include/gnatcoll_core \
        --build-var=LIBRARY_TYPE --build-var=GNATCOLL_BUILD \
        --build-var=GNATCOLL_CORE_BUILD gnatcoll_core.gpr
autoconf.cgpr: error: Unknown charset "UTF-8"
autoconf.cgpr:1:01: error: Expected Identifier, got Termination
gprinstall: "gnatcoll_core.gpr" processing failed
make: *** [Makefile:237: install-static] Error 4
```

**Comment by t-14** [comment]
@fastrgv as the readme says, you will need to install libgpr from gprbuild project as a prerequisite; or, you can build using gnatcoll-core.gpr which doesn't have libgpr dependency, in that case you won't.

@KhazAkar I am not sure I understand the "Either that, or" part, that looks like a different issue (not 100% sure but I think you need to update gprinstall for that one)
