### ISSUE TITLE
Does `gnatcoll_terminal_width` check ioctl return value? (possible UB?)

### ISSUE THREAD

**Issue by atalii** [AdaCore/gnatcoll-core#82]
I just took a quick look at `gnatcoll_terminal_width` (below), and it doesn't seem that the return value or errno is checked before accessing the winsize struct. Am I being overzealous, or is this UB?

```c
// snipped out windows code and func signature
#ifdef TIOCGWINSZ
    struct winsize w;
    ioctl(forStderr ? 1 : 0, TIOCGWINSZ, &w);
    return w.ws_col;
````

**Comment by Jicquel** [comment]
@atalii fix merged here: https://github.com/AdaCore/gnatcoll-core/commit/f985f02a5454cdcb94e6e39fff688b3a28f6df10
