### ISSUE TITLE
GNATCOLL.CONFIG crash on fuzzing (gnatcoll-templates.adb:252 range check failed)

### ISSUE THREAD

**Issue by touisteur** [AdaCore/gnatcoll-core#9]
Hi,

through the same method as #8 I stumbled upon a CONSTRAINT_ERROR while loading corrupted files with GNATCOLL.CONFIG.

Reproducers are there : [gnatcoll-templates.adb-252.zip](https://github.com/AdaCore/gnatcoll-core/files/1503451/gnatcoll-templates.adb-252.zip)

And the test program is in issue #8 .

Also with GNATCOLL GPL 2016...

I'll stop the fuzzing here, please let me know if you're interested that I try a bit further.

BR.
Lionel

**Comment by Nikokrock** [comment]
Fuzz tests you submitted are now passing. I did not use them though to make the final tests. Thanks again for your reports
