### ISSUE TITLE
Makefile: make clean issues unrecognized argument '--add-gpr-path', gprproject/gprbuild.py: self.gpr_paths incorrectly set in GPRTool.__init__ 

### ISSUE THREAD

**Issue by dsauvage** [AdaCore/gnatcoll-core#90]
1. Makefile: make clean issues unrecognized argument '--add-gpr-path'
```
.//projects/gnatcoll_projects.gpr.py clean --add-gpr-path=local-install/share/gpr
usage: gnatcoll_projects.gpr.py [-h] {build,clean,install,uninstall} ...
gnatcoll_projects.gpr.py: error: unrecognized arguments: --add-gpr-path=local-install/share/gpr
make: *** [Makefile:133: clean] Error 2
```
Removing the 3 unrecognized arguments `--add-gpr-path=local-install/share/gpr` in the clean section fixes the issue
```
diff --git a/Makefile b/Makefile
index d0fb58fb..318067c9 100644
--- a/Makefile
+++ b/Makefile
@@ -130,9 +130,9 @@ install:
 ###########
 
 clean:
-       $(PYTHON) $(SOURCE_DIR)/projects/gnatcoll_projects.gpr.py clean --add-gpr-path=local-install/share/gpr
-       $(PYTHON) $(SOURCE_DIR)/core/gnatcoll_core.gpr.py clean --add-gpr-path=local-install/share/gpr
-       $(PYTHON) $(SOURCE_DIR)/minimal/gnatcoll_minimal.gpr.py clean --add-gpr-path=local-install/share/gpr
+       $(PYTHON) $(SOURCE_DIR)/projects/gnatcoll_projects.gpr.py clean
+       $(PYTHON) $(SOURCE_DIR)/core/gnatcoll_core.gpr.py clean
+       $(PYTHON) $(SOURCE_DIR)/minimal/gnatcoll_minimal.gpr.py clean
 
 # Let gprbuild handle parallelisation. In general, we don't support parallel
 # runs in this Makefile, as concurrent gprinstall processes may crash.
```
2. gprproject/gprbuild.py: self.gpr_paths incorrectly set in GPRTool.__init__ 
Moreover, fixing issue above is not sufficient. `self.gpr_paths` is incorrectly set in `GPRTool.__init__`, and patch below is required
```
diff --git a/gprproject/gprbuild.py b/gprproject/gprbuild.py
index ad1cdb14..02951ab8 100644
--- a/gprproject/gprbuild.py
+++ b/gprproject/gprbuild.py
@@ -85,7 +85,7 @@ class GPRTool:
         self.gnatcov = gnatcov
         self.symcc = symcc
         self.gpr_paths: list[str] = []
-        if self.gpr_paths:
+        if gpr_paths:
             self.gpr_paths = list(gpr_paths)
         else:
             self.gpr_paths = []
```

**Comment by Jicquel** [comment]
Hello @dsauvage, thank you for your contribution! Your patch is working correctly. Would you like to open a PR with your [commit](https://github.com/AdaLabs/gnatcoll-core/commit/158d9d070c8050d9768bcfebce5a49a978ac9099) ?

**Comment by dsauvage** [comment]
Hi @Jicquel, thanks for your message. I would rather not as in our commit we also replaced `python` by `python3` in python scripts headers.

**Comment by Jicquel** [comment]
Noted. Your Python 3 modification is also required, as the scripts fail with Python 3. 
If you want, you can create a pull request (PR) with two separate commits: one for the Python 3 patch and another for the other patches.
We can also handle the work internally by incorporating your patches and crediting you as a co-author (if you accept it), for instance.
Let me know which solution works best for you.

**Comment by dsauvage** [comment]
I would prefer you handle the work internally, as I am currently working on another issue on the gnatcoll-core build system.
on other AC repo the feedback loop was about a year, so I'm very happy to contribute to this repo ;-)

**Comment by Jicquel** [comment]
Hi @dsauvage, thanks a lot for your feedback! Your patches have been merged, you can find them in the following commits:
https://github.com/AdaCore/gnatcoll-core/commit/848bc46c179db172571fa7dc69e0d368fd90bc2d
https://github.com/AdaCore/gnatcoll-core/commit/26cf0159c63de1fae848f51ed4f7e1008896b2a5
https://github.com/AdaCore/gnatcoll-core/commit/55148a9fbc9a2faed512138c3b62cb66c2ac1852

I will close this issue, but feel free to re-open it if needed.
